// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"LL_StandingPicture","status":true,"description":"メッセージウィンドウ表示時に立ち絵を自動表示します。","parameters":{"sPictures":"[\"{\\\"id\\\":\\\"0\\\",\\\"imageName\\\":\\\"Nature_3\\\",\\\"origin\\\":\\\"0\\\",\\\"x\\\":\\\"498\\\",\\\"y\\\":\\\"298\\\",\\\"x2\\\":\\\"318\\\",\\\"y2\\\":\\\"298\\\",\\\"reverse\\\":\\\"-1\\\",\\\"scaleX\\\":\\\"100\\\",\\\"scaleY\\\":\\\"100\\\",\\\"opacity\\\":\\\"255\\\",\\\"blendMode\\\":\\\"0\\\"}\",\"{\\\"id\\\":\\\"1\\\",\\\"imageName\\\":\\\"Nature_2\\\",\\\"origin\\\":\\\"0\\\",\\\"x\\\":\\\"498\\\",\\\"y\\\":\\\"298\\\",\\\"x2\\\":\\\"318\\\",\\\"y2\\\":\\\"298\\\",\\\"reverse\\\":\\\"-1\\\",\\\"scaleX\\\":\\\"100\\\",\\\"scaleY\\\":\\\"100\\\",\\\"opacity\\\":\\\"255\\\",\\\"blendMode\\\":\\\"0\\\"}\"]","transition":"1","transition2":"1"}}
];
